version: "3.4"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    networks:
      - combined-network

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: applications_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - combined-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - combined-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - combined-network
    depends_on:
      - application

  application:
    build: ./application
    container_name: application
    depends_on:
      - db
    networks:
      - combined-network

networks:
  combined-network:
    driver: bridge